Update utils/bin/ocm-login-owner
Co-authored-by: Tomas Dabašinskas <todabasi@redhat.com>

diff --git a/utils/bin/ocm-login-owner b/utils/bin/ocm-login-owner
--- a/utils/bin/ocm-login-owner
+++ b/utils/bin/ocm-login-owner
@@ -5,15 +5,15 @@ CLUSTERID=$1
 
 CLI="${CLI:-ocm}"
 if [[ "${CLI}" == "ocm" ]]; then
-  OCM_LIST_ADDITIONAL_ARG='--managed --columns id,name,api.url,openshift_version,region.id,state,external_id,ccs.enabled';
-  LOGIN_ENV='--url';
+  OCM_LIST_ADDITIONAL_ARG='--managed --columns id,name,api.url,openshift_version,region.id,state,external_id,ccs.enabled'
+  LOGIN_ENV='--url'
 elif [[ "${CLI}" == "moactl" ]]; then
-  LOGIN_ENV='--env';
+  LOGIN_ENV='--env'
 fi
 
 if [ "x${OFFLINE_ACCESS_TOKEN}" == "x" ]; then
-  echo "FAILURE: must set env variable OFFLINE_ACCESS_TOKEN";
-  exit 1;
+  echo "FAILURE: must set env variable OFFLINE_ACCESS_TOKEN"
+  exit 1
 fi
 
 if [ "$OCM_URL" == "" ];
